// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOhy8IeNWaHq3OHKP8Hj55xF4CCCBHwc',
    appId: '1:696215377240:web:8b77658e6c01c64248812d',
    messagingSenderId: '696215377240',
    projectId: 'flutter-firebase-3d82b',
    authDomain: 'flutter-firebase-3d82b.firebaseapp.com',
    storageBucket: 'flutter-firebase-3d82b.firebasestorage.app',
    measurementId: 'G-T8HG54J9FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7H61RCePk39FEaGKwd1L5Q7BTd6nXSmE',
    appId: '1:696215377240:android:f822154a4278bb0d48812d',
    messagingSenderId: '696215377240',
    projectId: 'flutter-firebase-3d82b',
    storageBucket: 'flutter-firebase-3d82b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf8BFXW-6HElDYGqhIvop1uB_E53toSCQ',
    appId: '1:696215377240:ios:ff6bea0e2708634248812d',
    messagingSenderId: '696215377240',
    projectId: 'flutter-firebase-3d82b',
    storageBucket: 'flutter-firebase-3d82b.firebasestorage.app',
    iosBundleId: 'com.example.realProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQOhy8IeNWaHq3OHKP8Hj55xF4CCCBHwc',
    appId: '1:696215377240:web:dd983e6303394ac548812d',
    messagingSenderId: '696215377240',
    projectId: 'flutter-firebase-3d82b',
    authDomain: 'flutter-firebase-3d82b.firebaseapp.com',
    storageBucket: 'flutter-firebase-3d82b.firebasestorage.app',
    measurementId: 'G-XBR9JH09VT',
  );
}
